In [1]:
import torch

In [2]:
import numpy as np

In [3]:
arr = [[1,2],[3,4]]
arr = np.array(arr)

In [4]:
arr

array([[1, 2],
       [3, 4]])

In [8]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [19]:
torch.manual_seed(41)
torch.rand(2,2)

tensor([[0.2364, 0.2266],
        [0.8005, 0.1692]])

In [16]:
np.random.seed(41)
np.random.rand(2,2)

array([[0.25092362, 0.04609582],
       [0.67681624, 0.04346949]])

In [17]:
np.random.rand(2,2)

array([[0.1164237 , 0.60386569],
       [0.19093066, 0.66851572]])

In [20]:
torch.cuda.is_available()

True

In [21]:
torch.from_numpy(arr)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [22]:
t1 = torch.ones(3,3)
type(t1)

torch.Tensor

In [23]:
t2 = t1.numpy()
type(t2)

numpy.ndarray

In [24]:
t2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [25]:
if torch.cuda.is_available():
    t1.cuda()


In [26]:
t1.cpu()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
t1 = torch.Tensor([ [[1,2],[3,4]],[[5,6],[7,8]]  ])
t1.size()
t1.view(-1,4)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [36]:
a = np.array([[1,2],[5,6]], dtype='float')
b = np.array([[3,1],[7,0]], dtype='float')
ap = torch.from_numpy(a)
bp = torch.from_numpy(b)
print(ap+bp)

tensor([[ 4.,  3.],
        [12.,  6.]], dtype=torch.float64)


In [37]:
ap.add_(bp)

tensor([[ 4.,  3.],
        [12.,  6.]], dtype=torch.float64)

In [40]:
ap.mean(dim=1)
ap.std(dim=0)

tensor([5.6569, 2.1213], dtype=torch.float64)

In [43]:
from torch.autograd import Variable
x = Variable(torch.ones(2), requires_grad=True)
y = 5*(x + 1) ** 2
o = y.mean()
o.backward()
x.grad

tensor([10., 10.])